#!/bin/bash
javac ~/java/jdressel/DerporiaPremium/Derporia.java
javac ~/java/jdressel/DerporiaPremium/Results.java
cp ~/java/jdressel/DerporiaPremium/Derporia.class /data/apps-swe432/swe432/WEB-INF/classes/jdressel/DerporiaPremium/Derporia.class
cp ~/java/jdressel/DerporiaPremium/Results.class /data/apps-swe432/swe432/WEB-INF/classes/jdressel/DerporiaPremium/Results.class

